# Form implementation generated from reading ui file 'preference_menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Ui.preference_menu_ui import Ui_MainWindow


class PreferenceMainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.applications_pushButton.clicked.connect(self.applications_clicked)

        self.interviews_pushButton.clicked.connect(self.interviews_clicked)
        
        self.mentor_meeting_pushButton.clicked.connect(self.mentor_meeting_clicked)
        self.bact_menu_pushButton.clicked.connect(self.bact_menu_clicked)
        self.exit_pushButton.clicked.connect(self.exit_clicked)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preference Menu"))
        self.bact_menu_pushButton.setText(_translate("MainWindow", "Back to Menu"))
        self.exit_pushButton.setText(_translate("MainWindow", "Exit"))
        self.interviews_pushButton.setText(_translate("MainWindow", "Interviews"))
        self.mentor_meeting_pushButton.setText(_translate("MainWindow", "Mentor Meeting"))
        self.applications_pushButton.setText(_translate("MainWindow", "Applications"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'__Inter_46a1ea\',\'__Inter_Fallback_46a1ea\',\'system-ui\',\'arial\'; font-size:10pt; font-weight:600; color:#ffffff;\">CRM -Preference Menu</span></p></body></html>"))


    def applications_clicked(self):
        from  applications_page import Ui_applications_page_MainWindow
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_applications_page_MainWindow()
        self.ui.setupUi(self.MainWindow) 
        self.MainWindow.show()
        
        

    def interviews_clicked(self):
        from interviews_page import Ui_interviews_page_MainWindow
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_interviews_page_MainWindow()
        self.ui.setupUi(self.MainWindow) 
        self.MainWindow.show()
        


    def mentor_meeting_clicked(self):
        from mentor_interview_page import Ui_mentor_interviews_page_MainWindow
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_mentor_interviews_page_MainWindow()
        self.ui.setupUi(self.MainWindow) 
        self.MainWindow.show()
        

    def bact_menu_clicked(self):
        from login_window import Ui_MainWindow
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.MainWindow) 
        self.MainWindow.show()
        
       
        

    def exit_clicked(self):
        from PyQt6.QtWidgets import QApplication, QMainWindow, QPushButton
        QApplication.instance().quit()        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = PreferenceMainWindow()
    window.show()
    sys.exit(app.exec())
